INSERT INTO TB_PROFILES (ID, DATA_CRIACAO, NOME, DATA_DE_ATUALIZACAO ) VALUES (1, CURRENT_TIMESTAMP(), 'Admin', CURRENT_TIMESTAMP());
INSERT INTO TB_USUÁRIOS (ID, ATIVO, DATA_CRIACAO, EMAIL, NOME, SENHA, DATA_DE_ATUALIZACAO, PROFILE_ID) VALUES (1, TRUE, CURRENT_TIMESTAMP(), 'gabriel_more@hotmail.com', 'Gabriel Maia', '$2a$10$htvQ1StZEN2vFN3dzyyg.ObsrkWknrVgq69dr4xMwzKG1lm2DPO7S',  CURRENT_TIMESTAMP(), 1);

INSERT INTO TB_PROFILES_USERS VALUES (1,1);

INSERT INTO TB_PERMISSIONS VALUES (1, CURRENT_TIMESTAMP(), 'ADC', CURRENT_TIMESTAMP());

INSERT INTO TB_PERMISSION_PROFILE  VALUES (1,1);